#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// --- Mini args parser ---
const args = process.argv.slice(2);
const argv = { dir: '.', output: 'repo_context.md', ignore: '', help: false };

for (let i = 0; i < args.length; i++) {
    if (args[i] === '-h' || args[i] === '--help') argv.help = true;
    else if (args[i] === '-d' || args[i] === '--dir') argv.dir = args[++i];
    else if (args[i] === '-o' || args[i] === '--output') argv.output = args[++i];
    else if (args[i] === '-i' || args[i] === '--ignore') argv.ignore = args[++i];
}

function printSponsorMessage() {
    console.log('\n\x1b[36m=================================================================\x1b[0m');
    console.log('\x1b[1m\x1b[35m?? Do you find repo2llm useful for your AI coding sessions? ?¨\x1b[0m');
    console.log('If this tool saved you time, please consider supporting its development:');
    console.log('\n?? \x1b[32mhttps://polar.sh/albert-dev\x1b[0m ??');
    console.log('\x1b[36m=================================================================\x1b[0m\n');
}

if (argv.help) {
    console.log(`
repo2llm - Pack your codebase for LLMs (Zero Dependencies)

Usage:
  npx repo2llm [options]

Options:
  -d, --dir <path>     Directory to pack (default: current directory)
  -o, --output <file>  Output markdown file (default: repo_context.md)
  -i, --ignore <paths> Additional comma-separated paths to ignore
  -h, --help           Show this help message

Examples:
  npx repo2llm
  npx repo2llm -d ./src -o output.md -i "tests,docs"
`);
    printSponsorMessage();
    process.exit(0);
}

const targetDir = path.resolve(process.cwd(), argv.dir);
const outputFile = path.resolve(process.cwd(), argv.output);

// --- Mini gitignore parser ---
function parseGitignore(content) {
    return content.split('\n')
        .map(line => line.trim())
        .filter(line => line && !line.startsWith('#'))
        .map(line => {
            let pattern = line.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
            pattern = pattern.replace(/\\\*/g, '.*');
            pattern = pattern.replace(/\\\?/g, '.');
            if (!pattern.startsWith('.*')) {
                pattern = '^' + pattern;
            }
            return new RegExp(pattern);
        });
}

const defaultIgnores = [
    '.git', 'node_modules', 'dist', 'build', 'coverage', '.next',
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', path.basename(outputFile)
];

if (argv.ignore) {
    defaultIgnores.push(...argv.ignore.split(',').map(s => s.trim()));
}

let ignoreRegexes = defaultIgnores.map(ig => new RegExp('^' + ig.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&').replace(/\\\*/g, '.*')));

const gitignorePath = path.join(targetDir, '.gitignore');
if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf8');
    ignoreRegexes = ignoreRegexes.concat(parseGitignore(content));
}

function isIgnored(relativePath) {
    return ignoreRegexes.some(regex => regex.test(relativePath));
}

function walk(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    for (const file of list) {
        const filePath = path.join(dir, file);
        const relativePath = path.relative(targetDir, filePath).replace(/\\/g, '/');
        
        if (isIgnored(relativePath)) continue;
        
        const stat = fs.statSync(filePath);
        if (stat && stat.isDirectory()) {
            results = results.concat(walk(filePath));
        } else {
            results.push(filePath);
        }
    }
    return results;
}

function getExtension(filename) {
    const ext = path.extname(filename).toLowerCase();
    return ext ? ext.substring(1) : '';
}

function isBinary(buffer) {
    for (let i = 0; i < Math.min(buffer.length, 4000); i++) {
        if (buffer[i] === 0) return true;
    }
    return false;
}

async function main() {
    console.log(`\x1b[34m[repo2llm]\x1b[0m Scanning directory: ${targetDir}`);
    
    let files;
    try {
        files = walk(targetDir);
    } catch (err) {
        console.error(`\x1b[31mError scanning directory: ${err.message}\x1b[0m`);
        process.exit(1);
    }
    
    let outputContent = `# Repository Context\n\nGenerated by \`repo2llm\`.\n\n`;
    let processedCount = 0;
    
    for (const file of files) {
        const relativePath = path.relative(targetDir, file).replace(/\\/g, '/');
        
        try {
            const buffer = fs.readFileSync(file);
            if (isBinary(buffer)) continue;
            
            const content = buffer.toString('utf8');
            const ext = getExtension(file);
            
            outputContent += `## ${relativePath}\n\n`;
            outputContent += `\`\`\`${ext}\n`;
            outputContent += content;
            if (!content.endsWith('\n')) outputContent += '\n';
            outputContent += `\`\`\`\n\n`;
            processedCount++;
        } catch (err) {
            console.warn(`\x1b[33mWarning: Could not read file ${relativePath}: ${err.message}\x1b[0m`);
        }
    }
    
    try {
        fs.writeFileSync(outputFile, outputContent, 'utf8');
        console.log(`\x1b[32m[Success]\x1b[0m Packed ${processedCount} files into \x1b[1m${argv.output}\x1b[0m`);
        printSponsorMessage();
    } catch (err) {
        console.error(`\x1b[31mError writing output file: ${err.message}\x1b[0m`);
        process.exit(1);
    }
}

main();
